### PR TITLE
chore: Remove battery icon fix extension

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This currently requires a `full-upgrade` instead of a regular `upgrade`:

```
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  gnome-shell-extension-pop-battery-icon-fix
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  pop-icon-theme
The following packages will be upgraded:
  pop-session
```

If I proceed with the above (a regular `upgrade`), I get this on subsequent upgrades:

```
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  gnome-shell-extension-pop-battery-icon-fix
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  pop-icon-theme
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

This also results in the Pop!_Shop showing 2 updates available but not being able to install them.

**Comment by ids1024** [comment]
It doesn't seem quite semantically correct, but perhaps https://github.com/pop-os/icon-theme/pull/78 could include a `Provides` for `gnome-shell-extension-pop-battery-icon-fix` in addition to the `Conflicts`. That would hopefully make it upgrade with `apt upgrade`.

Normally `apt upgrade` doesn't remove packages (but can install new packages, which `apt-get upgrade` doesn't do by default).

**Comment by jacobgkau** [comment]
With the latest version of `pop-icon-theme` from https://github.com/pop-os/icon-theme/pull/78 (which `Provides: gnome-shell-extension-pop-battery-icon-fix`), I'm still seeing the same issue with `pop-icon-theme` getting held back:

```
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  gnome-shell-extension-pop-battery-icon-fix
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  pop-icon-theme
The following packages will be upgraded:
  pop-session
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 3,884 B of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://apt.pop-os.org/staging/iconfix groovy/main amd64 pop-session all 5.0.0~1608309967~20.10~a8ac1eb [3,884 B]
Fetched 3,884 B in 0s (42.0 kB/s)      
(Reading database ... 212395 files and directories currently installed.)
Preparing to unpack .../pop-session_5.0.0~1608309967~20.10~a8ac1eb_all.deb ...
Unpacking pop-session (5.0.0~1608309967~20.10~a8ac1eb) over (5.0.0~1604701048~20.10~e3640fb) ...
Setting up pop-session (5.0.0~1608309967~20.10~a8ac1eb) ...
Processing triggers for libglib2.0-0:amd64 (2.66.1-2) ...
system76@pop-os:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  gnome-shell-extension-pop-battery-icon-fix
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  pop-icon-theme
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
system76@pop-os:~$ apt policy pop-icon-theme 
pop-icon-theme:
  Installed: 2.1.0~1602083697~20.10~5a9a850
  Candidate: 2.1.0~1608613952~20.10~25ade76
  Version table:
     2.1.0~1608613952~20.10~25ade76 1002
       1002 http://apt.pop-os.org/staging/iconfix groovy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/iconfix groovy/main i386 Packages
 *** 2.1.0~1602083697~20.10~5a9a850 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
     2.1.0~1583343731~20.04~11f18cb~ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
```

Maybe we need an empty transitional package in the control file, like we used for the desktop icons plugin? (That way, `pop-battery-icon-fix` would be "updated," rather than removed.)

**Comment by mmstick** [comment]
Made it a transitional package in the icon-theme PR

**Comment by jacobgkau** [comment]
It installs with regular `apt upgrade` now, but something else is wrong with the `icon-theme` PR now. After installing, I default to Adwaita icons and there is no option for the Pop icon theme in GNOME Tweaks:

icon-theme-pr78

I can see in the built .deb package that the actual icons are missing (new package on the left, old one on the right):

Screenshot from 2020-12-22 15-08-29

I tried building locally and saw the same thing, so it's not a CI quirk. No idea why it's happening, but if I comment out the four new lines from `debian/control` and rebuild (the `icon-theme` package), the icons come back, so it seems related.

**Comment by jacobgkau** [comment]
I am still seeing Adwaita icons after installing this PR (and https://github.com/pop-os/icon-theme/pull/78) due to missing icons in `/usr/share/icons/Pop`.

**Comment by jacobgkau** [comment]
After the last commit (https://github.com/pop-os/icon-theme/pull/78/commits/4a61aa96dd282b6fe0cd2d1dfb06ef83fdb1c027) on the icon-theme PR, everything seems to be working.

- I'm able to install the update with the Pop!_Shop or a regular `apt upgrade`.
- After rebooting, the Pop battery icons are now used on the login screen, and are still used once logged in.
- After autoremoving `gnome-shell-extension-pop-battery-icon-fix` and rebooting, the correct icons are still used in all locations.

Tested on Groovy and Focal.

**Review by jacobgkau — APPROVED** [review]

**Comment by jackpot51** [comment]
The following should have been updated:

https://github.com/pop-os/session/blob/master_focal/usr/share/gnome-shell/modes/pop.json#L8
https://github.com/pop-os/session/blob/master_focal/debian/pop-session.gsettings-override#L118

**Comment by mmstick** [comment]
Will update them

**Comment by jackpot51** [comment]
Also, in pop.json, ding is not listed

**Pull request merged**
