### PR TITLE
Disable the super+number bindings

### PR DESCRIPTION
**Pull request by ids1024**
This is a workaround that should address https://github.com/pop-os/shell/issues/196. Ultimately that seems like an issue with key binding handling in Mutter (https://gitlab.gnome.org/GNOME/mutter/-/issues/1314), but this is simpler and these bindings don't seem too useful in vanilla Gnome anyway.

(As discussed in Slack.)

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Disables the Super+# bindings as advertised.

Also confirmed that after this update is applied, rebooting with the German keyboard layout and then using Super+7 works to open the launcher (the German layout uses Shift-7 to produce a /.)

**Comment by jsj1027** [comment]
These keybinds are super useful in vanilla gnome. Infact it is a large part of my workflow.
These keybinds are also available in windows where I also use them extensively. There should be an option to disable this behaviour, or it should at least only activate when a European keyboard is detected.

**Comment by jackpot51** [comment]
I agree, after seeing user feedback, that we removed them too early. We have a plan to add a toggle for turning this feature on and off in gnome-control-center that @ids1024 is working on

**Comment by ids1024** [comment]
The terminal command in https://github.com/pop-os/session/issues/21#issuecomment-658434530 is probably the best workaround to re-enable this in lieu of a GUI option. It has the same effect a setting in Gnome Control Center would have.

**Comment by Ulimn** [comment]
What a fucking lazy approach... 🤦🏻‍♂️

**Comment by jackpot51** [comment]
What is lazy @Ulimn is coming here with a comment like that and nothing else to offer

**Comment by Ulimn** [comment]
If pull requests like these are approved and merged, I don’t want to do anything with it.

**Comment by jackpot51** [comment]
@Ulimn Great! What are you still doing here then?

**Pull request merged**
